name: Build, Push, and Deploy to EC2

on:
  push:
    branches:
      - main  # Triggers the workflow on push to the main branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags:  ${{ secrets.DOCKER_USERNAME }}/fileselectorapp:latest  # Change this to your Docker Hub  ${{ secrets.DOCKER_USERNAME }}/repo

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to EC2
        run: |
          sudo ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
            docker pull  ${{ secrets.DOCKER_USERNAME }}/fileselectorapp:latest
            docker stop fileselectorapp || true
            docker rm fileselectorapp || true
            docker run -d -p 5006:5006 --name fileselectorapp  ${{ secrets.DOCKER_USERNAME }}/fileselectorapp:latest
          EOF
