name: Publish Docker App

on:
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags:  ${{ secrets.DOCKER_USERNAME }}/fileselectorapp:latest 

      - name: Run Docker container
        run: |
          docker run -d --name fileselectorapp -p 5006:5006 ${{ secrets.DOCKER_USERNAME }}/fileselectorapp:latest

      - name: Publish Port for GitHub Runner
        run: echo "::set-output name=port::5006"
