name: Publish Docker App to GHCR

on:
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.G_TOKEN }}

      - name: Build and Push Docker image to GHCR
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}/fileselectorapp:latest

      - name: Run Docker container
        run: |
          docker run -d --name fileselectorapp -p 5006:5006 ghcr.io/${{ github.repository }}/fileselectorapp:latest

      - name: Publish Port for GitHub Runner
        run: echo "::set-output name=port::5006"
